name: Firebase App Hosting

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cambiado de read a write para que pueda generar archivos si es necesario

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # FORZAMOS LA CREACIÃ“N DEL LOCK FILE SI NO EXISTE
      - name: Install Dependencies
        run: |
          npm install --package-lock-only
          npm install

      - name: Build
        run: npm run build

      - name: Deploy to Firebase App Hosting
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            npx firebase-tools@latest deploy --only apphosting:my-web-app --project TU_PROYECTO_PROD --non-interactive
          else
            npx firebase-tools@latest deploy --only apphosting:my-web-app-staging --project studio-4350140400-a3f8f --non-interactive
          fi
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
